kind: pipeline
name: default

workspace:
  base: /src
  path: gitfolio

clone:
  disable: true

steps:
- name: clone
  image: docker:git
  commands:
    - git clone https://github.com/rohit-smpx/rohit-smpx.github.io .

- name: build
  image: node:12
  commands:
    - yarn global add rohit-smpx/gitfolio
    - gitfolio update

- name: git_push
  image: plugins/gh-pages
  settings:
    username: rohit-drone
    user_name: drone
    user_email: drone@boring.download
    password:
      from_secret: github_token
    pages_directory: ./
    target_branch: master
    temporary_base: .tmp

# trigger:
#   target:
#     build
  # Cron does not work on cloud.drone.io (https://discourse.drone.io/t/cron-on-cloud-drone-io/3899)
...
