kind: pipeline
name: default

workspace:
  base: /src
  path: gitfolio

steps:
- name: build
  image: node:12
  commands:
    - yarn global add rohit-gohri/gitfolio
    - gitfolio update

- name: download
  image: abihf/wget
  commands:
    - wget -O ./resume/RohitGohri.pdf https://go.boring.download/resume
  when:
    target:
      - resume
      - build


- name: commit-and-push-pages
  image: docker:git
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
    - git config user.email "drone@boring.download"
    - git config user.name "Drone User"
    - git add --all
    - git commit -m "Updating site, `date`"
    - git remote add origin-pages https://$GITHUB_TOKEN@github.com/$DRONE_REPO.git > /dev/null 2>&1
    - git push --set-upstream origin-pages master
  when:
    target:
      - resume
      - build

trigger:
  target:
    exclude: 
      - github-pages
  
# Cron does not work on cloud.drone.io (https://discourse.drone.io/t/cron-on-cloud-drone-io/3899)
...
