kind: pipeline
name: default

workspace:
  base: /src
  path: gitfolio

steps:
- name: build
  image: node:12
  commands:
    - yarn global add rohit-smpx/gitfolio
    - gitfolio update

- name: download
  image: abihf/wget
  commands:
    - wget -O ./resume/RohitGohri.pdf https://go.boring.download/resume
  when:
    target:
      - resume
      - build

- name: git_push
  image: plugins/gh-pages
  settings:
    username: rohit-drone
    user_name: drone
    user_email: drone@boring.download
    password:
      from_secret: github_token
    pages_directory: ./
    target_branch: master
    temporary_base: .tmp
  when:
    target:
      - resume
      - build

trigger:
  target:
    exclude: 
      - github-pages
  
# Cron does not work on cloud.drone.io (https://discourse.drone.io/t/cron-on-cloud-drone-io/3899)
...
